/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan.panels;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tampilan.obj.Koneksi;

/**
 *
 * @author ACER
 */
public class FormTransaksi extends javax.swing.JPanel {

    private DefaultTableModel modelProduk;
    private DefaultTableModel modelKeranjang;

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        setupTable();
        loadDataProduk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        tblDaftarProduk = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCariProduk = new javax.swing.JTextField();
        txtProduk = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJumlahProduk = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Menu", "Kategori", "Harga"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tblDaftarProduk.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 311;
        gridBagConstraints.ipady = 413;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanel1.add(tblDaftarProduk, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari item");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariProdukActionPerformed(evt);
            }
        });
        txtCariProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariProdukKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        jPanel1.add(txtCariProduk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        jPanel1.add(txtProduk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        jPanel1.add(txtHarga, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        jPanel1.add(txtJumlahProduk, gridBagConstraints);

        btnTambah.setBackground(new java.awt.Color(0, 153, 51));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Add");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 9, 0, 6);
        jPanel1.add(btnTambah, gridBagConstraints);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Total bayar");

        jLabel3.setText("Cash");

        jLabel4.setText("Kembali");

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKembali)
                            .addComponent(txtCash)
                            .addComponent(txtTotalBayar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton1)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jPanel3, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kasir Toko Kelontong");
        jPanel1.add(jLabel5, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariProdukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prosesBayar();
        try {
            double total = Double.parseDouble(txtTotalBayar.getText());
            double cash = Double.parseDouble(txtCash.getText());

            if (cash < total) {
                JOptionPane.showMessageDialog(this, "Uang cash kurang!");
                return;
            }

            double kembali = cash - total;
            txtKembali.setText(String.valueOf(kembali));

            // JALANKAN PROSES SIMPAN
            int idTransaksi = simpanKeDatabase(total, cash, kembali);

            if (idTransaksi != -1) {
                // MUNCULKAN NOTA
                tampilkanNota(idTransaksi, total, cash, kembali);

                // RESET FORM
                modelKeranjang.setRowCount(0);
                txtTotalBayar.setText("0");
                txtCash.setText("");
                txtKembali.setText("");
                loadDataProduk(); // Refresh stok di tabel kiri
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan nominal angka yang benar!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prosesBayar() {
        try {
            double total = Double.parseDouble(txtTotalBayar.getText().replace(",", ""));
            double cash = Double.parseDouble(txtCash.getText());

            if (cash < total) {
                JOptionPane.showMessageDialog(this, "Uang Cash Kurang!");
                return;
            }

            double kembali = cash - total;
            txtKembali.setText(String.valueOf(kembali));

            Connection K = tampilan.obj.Koneksi.Go();
            K.setAutoCommit(false);

            // 1. Insert ke tabel transaksi (Sesuaikan kolom dengan SQL Anda)
            String sqlT = "INSERT INTO transaksi (tanggal, id_user, total_harga, bayar, kembalian, metode_pembayaran) VALUES (NOW(), ?, ?, ?, ?, 'cash')";
            java.sql.PreparedStatement psT = K.prepareStatement(sqlT, java.sql.Statement.RETURN_GENERATED_KEYS);
            psT.setInt(1, 1);
            psT.setDouble(2, total);
            psT.setDouble(3, cash);
            psT.setDouble(4, kembali);
            psT.executeUpdate();

            java.sql.ResultSet rs = psT.getGeneratedKeys();
            int idTrans = 0;
            if (rs.next()) {
                idTrans = rs.getInt(1);
            }

            // 2. Insert ke detail_transaksi
            String sqlD = "INSERT INTO detail_transaksi (id_transaksi, id_produk, jumlah, harga_satuan, subtotal) "
                    + "VALUES (?, (SELECT id_produk FROM produk WHERE nama_produk=? LIMIT 1), ?, ?, ?)";
            java.sql.PreparedStatement psD = K.prepareStatement(sqlD);

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                psD.setInt(1, idTrans);
                psD.setString(2, jTable2.getValueAt(i, 0).toString());
                psD.setInt(3, Integer.parseInt(jTable2.getValueAt(i, 2).toString()));
                psD.setDouble(4, Double.parseDouble(jTable2.getValueAt(i, 1).toString()));
                psD.setDouble(5, Double.parseDouble(jTable2.getValueAt(i, 3).toString()));
                psD.addBatch();
            }
            psD.executeBatch();
            K.commit();

            // Panggil Nota
            tampilkanNota(idTrans, total, cash, kembali);

            // Reset
            modelKeranjang.setRowCount(0);
            txtTotalBayar.setText("0");
            txtCash.setText("");
            loadDataProduk();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }
    }

    private int simpanKeDatabase(double total, double bayar, double kembali) {
        int id = -1;
        try {
            Connection K = tampilan.obj.Koneksi.Go();
            K.setAutoCommit(false); // Mode transaksi aman

            // 1. Simpan Header ke tabel 'transaksi'
            String sqlT = "INSERT INTO transaksi (id_user, total_harga, bayar, kembalian, metode_pembayaran) VALUES (?, ?, ?, ?, 'cash')";
            java.sql.PreparedStatement psT = K.prepareStatement(sqlT, java.sql.Statement.RETURN_GENERATED_KEYS);
            psT.setInt(1, 1); // ID User Kasir (sementara 1)
            psT.setDouble(2, total);
            psT.setDouble(3, bayar);
            psT.setDouble(4, kembali);
            psT.executeUpdate();

            java.sql.ResultSet rs = psT.getGeneratedKeys();
            if (rs.next()) {
                id = rs.getInt(1);
            }

            // 2. Simpan Detail & Update Stok
            String sqlD = "INSERT INTO detail_transaksi (id_transaksi, id_produk, jumlah, harga_satuan, subtotal) "
                    + "VALUES (?, (SELECT id_produk FROM produk WHERE nama_produk=?), ?, ?, ?)";
            String sqlS = "UPDATE produk SET stok = stok - ? WHERE nama_produk = ?";

            java.sql.PreparedStatement psD = K.prepareStatement(sqlD);
            java.sql.PreparedStatement psS = K.prepareStatement(sqlS);

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String nama = jTable2.getValueAt(i, 0).toString();
                double harga = Double.parseDouble(jTable2.getValueAt(i, 1).toString());
                int qty = Integer.parseInt(jTable2.getValueAt(i, 2).toString());
                double sub = Double.parseDouble(jTable2.getValueAt(i, 3).toString());

                // Tambah ke Detail
                psD.setInt(1, id);
                psD.setString(2, nama);
                psD.setInt(3, qty);
                psD.setDouble(4, harga);
                psD.setDouble(5, sub);
                psD.addBatch();

                // Potong Stok
                psS.setInt(1, qty);
                psS.setString(2, nama);
                psS.addBatch();
            }
            psD.executeBatch();
            psS.executeBatch();

            K.commit(); // Simpan permanen
        } catch (Exception e) {
            id = -1;
            System.err.println("Gagal simpan: " + e.getMessage());
        }
        return id;
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String nama = jTable1.getValueAt(row, 0).toString();
            String harga = jTable1.getValueAt(row, 2).toString();

            txtProduk.setText(nama);
            txtHarga.setText(harga);
            txtJumlahProduk.setText("1");
            txtJumlahProduk.requestFocus();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            String nama = txtProduk.getText();
            double harga = Double.parseDouble(txtHarga.getText());
            int qty = Integer.parseInt(txtJumlahProduk.getText());
            double subtotal = harga * qty;

            modelKeranjang.addRow(new Object[]{nama, harga, qty, subtotal});

            // Hitung Total Bayar otomatis
            hitungTotal();

            // Reset input
            txtProduk.setText("");
            txtHarga.setText("");
            txtJumlahProduk.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pilih produk dan isi jumlah dengan benar!");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtCariProdukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariProdukKeyReleased
        String ketikan = txtCariProduk.getText();
        if (ketikan.isEmpty()) {
            loadDataProduk(); // Jika kosong, tampilkan semua lagi
        } else {
            cariData(ketikan); // Jika ada isi, cari yang sesuai
        }
    }//GEN-LAST:event_txtCariProdukKeyReleased

    private void hitungTotal() {
        double total = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            total += Double.parseDouble(jTable2.getValueAt(i, 3).toString());
        }
        txtTotalBayar.setText(String.valueOf(total));
    }

    public void loadDataProduk() {
        modelProduk.setRowCount(0); // Bersihkan tabel dulu
        try {
            Connection K = Koneksi.Go();
            Statement S = K.createStatement();
            // Query mengambil data produk
            String Q = "SELECT nama_produk, kategori, harga_jual FROM produk";
            ResultSet R = S.executeQuery(Q);

            while (R.next()) {
                Object[] data = {
                    R.getString("nama_produk"),
                    R.getString("kategori"),
                    R.getDouble("harga_jual")
                };
                modelProduk.addRow(data);
            }
        } catch (SQLException e) {
            System.err.println("Error Load Data: " + e.getMessage());
        }
    }

    private void setupTable() {
        // Setup Tabel Kiri (Daftar Produk dari DB)
        modelProduk = new DefaultTableModel();
        modelProduk.addColumn("Nama Produk");
        modelProduk.addColumn("Kategori");
        modelProduk.addColumn("Harga");
        jTable1.setModel(modelProduk);

        // Setup Tabel Kanan (Keranjang Belanja)
        modelKeranjang = new DefaultTableModel();
        modelKeranjang.addColumn("Nama");
        modelKeranjang.addColumn("Harga");
        modelKeranjang.addColumn("Qty");
        modelKeranjang.addColumn("Subtotal");
        jTable2.setModel(modelKeranjang);
    }

    public void cariData(String kunci) {
        modelProduk.setRowCount(0); // Kosongkan tabel dulu
        try {
            Connection K = Koneksi.Go();
            Statement S = K.createStatement();
            // Mencari berdasarkan nama_produk atau kategori
            String Q = "SELECT nama_produk, kategori, harga_jual FROM produk WHERE "
                    + "nama_produk LIKE '%" + kunci + "%' OR "
                    + "kategori LIKE '%" + kunci + "%'";
            ResultSet R = S.executeQuery(Q);

            while (R.next()) {
                Object[] data = {
                    R.getString("nama_produk"),
                    R.getString("kategori"),
                    R.getDouble("harga_jual")
                };
                modelProduk.addRow(data);
            }
        } catch (SQLException e) {
            System.err.println("Error Cari Data: " + e.getMessage());
        }
    }

    private void tampilkanNota(int id, double total, double cash, double kembali) {
        StringBuilder s = new StringBuilder();
        s.append("          TOKO KELONTONG          \n");
        s.append("       ID Transaksi: #").append(id).append("\n");
        s.append("==================================\n");
        s.append(String.format("%-16s %-4s %-10s\n", "Produk", "Qty", "Subtotal"));
        s.append("----------------------------------\n");

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            String nama = jTable2.getValueAt(i, 0).toString();
            String qty = jTable2.getValueAt(i, 2).toString();
            String sub = jTable2.getValueAt(i, 3).toString();
            if (nama.length() > 15) {
                nama = nama.substring(0, 13) + "..";
            }
            s.append(String.format("%-16s %-4s %-10s\n", nama, qty, sub));
        }

        s.append("----------------------------------\n");
        s.append(String.format("TOTAL     : Rp %,.0f\n", total));
        s.append(String.format("BAYAR     : Rp %,.0f\n", cash));
        s.append(String.format("KEMBALIAN : Rp %,.0f\n", kembali));
        s.append("==================================\n");
        s.append("    Terima Kasih Atas Kunjungan Anda   \n");

        javax.swing.JTextArea area = new javax.swing.JTextArea(s.toString());
        area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        area.setEditable(false);

        JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(area), "Pembayaran Berhasil", JOptionPane.PLAIN_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tblDaftarProduk;
    private javax.swing.JTextField txtCariProduk;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlahProduk;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
