/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan.panels;

import java.awt.Image;
import java.io.File;
import java.math.BigDecimal; // Gunakan BigDecimal
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tampilan.AddProduct;
import tampilan.EditProduct;
import tampilan.obj.Koneksi;
import tampilan.obj.Produk;

/**
 *
 * @author ACER
 */
public class ManageProducts extends javax.swing.JPanel {

    private static Produk selectedProduk; 

    public ManageProducts() {
        initComponents();
        RefreshData(); 
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTombol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPreview = new javax.swing.JPanel();
        lblImagePreview = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Data");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTombolLayout = new javax.swing.GroupLayout(panelTombol);
        panelTombol.setLayout(panelTombolLayout);
        panelTombolLayout.setHorizontalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        panelTombolLayout.setVerticalGroup(
            panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTombolLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit))
                .addGap(33, 33, 33))
        );

        add(panelTombol, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode", "Nama Produk", "Kategori", "Stok", "Harga Jual"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblImagePreview.setText("Preview Gambar");

        javax.swing.GroupLayout panelPreviewLayout = new javax.swing.GroupLayout(panelPreview);
        panelPreview.setLayout(panelPreviewLayout);
        panelPreviewLayout.setHorizontalGroup(
            panelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreviewLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        panelPreviewLayout.setVerticalGroup(
            panelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreviewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        add(panelPreview, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        AddProduct addDialog = new AddProduct(null, true);
        addDialog.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (selectedProduk == null) {
            JOptionPane.showMessageDialog(this, "Pilih produk yang ingin dihapus.");
            return;
        }

        int response = JOptionPane.showConfirmDialog(this,
                "Anda yakin ingin menghapus produk '" + selectedProduk.getNama() + "'?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                Connection K = Koneksi.Go();
                String sql = "DELETE FROM produk WHERE id_produk = ?";
                PreparedStatement PS = K.prepareStatement(sql);
                PS.setInt(1, selectedProduk.getId());
                PS.executeUpdate();

                // Hapus file gambar
                if (selectedProduk.getImagePath() != null && !selectedProduk.getImagePath().isEmpty()) {
                    File imgFile = new File("src/main/resources" + selectedProduk.getImagePath());
                    if (imgFile.exists()) {
                        imgFile.delete();
                    }
                }
                
                RefreshData(); 
                JOptionPane.showMessageDialog(this, "Produk berhasil dihapus.");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus produk: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (selectedProduk == null) {
            JOptionPane.showMessageDialog(this, "Pilih produk yang ingin diedit.");
            return;
        }
        EditProduct editDialog = new EditProduct(null, true);
        editDialog.P = selectedProduk;
        editDialog.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int n = jTable1.getSelectedRow();
        if (n == -1) {
            return;
        }

        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);

        int id = Integer.parseInt(jTable1.getValueAt(n, 0).toString());

        // Ambil data lengkap dari DB untuk menghindari error parsing DECIMAL
        try {
            Connection K = Koneksi.Go();
            PreparedStatement PS = K.prepareStatement("SELECT * FROM produk WHERE id_produk = ?");
            PS.setInt(1, id);
            ResultSet RS = PS.executeQuery();

            if (RS.next()) {
                selectedProduk = new Produk();
                selectedProduk.setId(RS.getInt("id_produk"));
                selectedProduk.setKodeProduk(RS.getString("kode_produk"));
                selectedProduk.setNama(RS.getString("nama_produk"));
                selectedProduk.setKategori(RS.getString("kategori"));
                selectedProduk.setStok(RS.getInt("stok"));
                selectedProduk.setHargaBeli(RS.getBigDecimal("harga_beli"));
                selectedProduk.setHargaJual(RS.getBigDecimal("harga_jual"));
                selectedProduk.setImagePath(RS.getString("image_path"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil detail produk: " + e.getMessage());
            return;
        }

        // Tampilkan gambar di preview
        String imagePath = selectedProduk.getImagePath();
        if (imagePath != null && !imagePath.isEmpty()) {
            try {
                ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
                Image img = icon.getImage().getScaledInstance(lblImagePreview.getWidth(), lblImagePreview.getHeight(), Image.SCALE_SMOOTH);
                lblImagePreview.setIcon(new ImageIcon(img));
                lblImagePreview.setText("");
            } catch (Exception e) {
                lblImagePreview.setIcon(null);
                lblImagePreview.setText("Gambar tidak ditemukan");
            }
        } else {
            lblImagePreview.setIcon(null);
            lblImagePreview.setText("Tidak ada gambar");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public static void RefreshData() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 

            Connection K = Koneksi.Go();
            Statement S = K.createStatement();
            // Ambil semua kolom
            String Q = "SELECT * FROM produk";
            ResultSet R = S.executeQuery(Q);

            while (R.next()) {
                // Sesuaikan dengan kolom tabel JTable (6 kolom)
                Object[] dataProduk = {
                    R.getInt("id_produk"),
                    R.getString("kode_produk"),
                    R.getString("nama_produk"),
                    R.getString("kategori"),
                    R.getInt("stok"),
                    R.getBigDecimal("harga_jual") // Tampilkan harga jual
                };
                model.addRow(dataProduk);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data produk: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JPanel panelPreview;
    private javax.swing.JPanel panelTombol;
    // End of variables declaration//GEN-END:variables
}
