/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.JPanel;
import tampilan.obj.Pegawai;
import tampilan.panels.ManageUers;
import tampilan.panels.Dashboard;
import tampilan.panels.FormTransaksi;
import tampilan.panels.ManageProducts;

/**
 *
 * @author ACER
 */
public class KasirPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KasirPage.class.getName());
    public static tampilan.obj.Pegawai P;

    /**
     * Creates new form KasirPage
     */
    public KasirPage() {
        initComponents();
        addViews(new Dashboard());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelPenggunaKasir = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelDashboard = new javax.swing.JLabel();
        labelTransaksi = new javax.swing.JLabel();
        labelLaporan = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(587, 50));

        labelPenggunaKasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPenggunaKasir.setText("Nama");
        labelPenggunaKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPenggunaKasirMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(434, Short.MAX_VALUE)
                .addComponent(labelPenggunaKasir)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPenggunaKasir)
                    .addComponent(jButton1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 389));

        labelDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDashboard.setForeground(new java.awt.Color(204, 204, 204));
        labelDashboard.setText("Dashboard");
        labelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDashboardMouseClicked(evt);
            }
        });

        labelTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        labelTransaksi.setText("Transaksi");
        labelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTransaksiMouseClicked(evt);
            }
        });

        labelLaporan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLaporan.setForeground(new java.awt.Color(204, 204, 204));
        labelLaporan.setText("Laporan");
        labelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLaporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLaporan)
                    .addComponent(labelTransaksi)
                    .addComponent(labelDashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelDashboard)
                .addGap(28, 28, 28)
                .addComponent(labelTransaksi)
                .addGap(26, 26, 26)
                .addComponent(labelLaporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        labelPenggunaKasir.setText(P.getNama());
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        LoginPage L = new LoginPage();
        L.setVisible(true);
        L.setExtendedState(Frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void labelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDashboardMouseClicked
        addViews(new Dashboard());
    }//GEN-LAST:event_labelDashboardMouseClicked

    private void labelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTransaksiMouseClicked
        addViews(new tampilan.panels.FormTransaksi());
    }//GEN-LAST:event_labelTransaksiMouseClicked

    private void labelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporanMouseClicked
        tampilan.panels.RiwayatTransaksi pnlRiwayat = new tampilan.panels.RiwayatTransaksi();
        pnlRiwayat.loadData();
        addViews(pnlRiwayat);
    }//GEN-LAST:event_labelLaporanMouseClicked

    private void labelPenggunaKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPenggunaKasirMouseClicked
        Profile P = new Profile(this, true);
        P.setVisible(true);
    }//GEN-LAST:event_labelPenggunaKasirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KasirPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelLaporan;
    private javax.swing.JLabel labelPenggunaKasir;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables

    private void addViews(javax.swing.JPanel Panel) {
        if (panelContent.getComponentCount() > 0) {
            panelContent.removeAll();
        }
        panelContent.add(Panel, BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }
}
